# -*- coding: utf-8 -*-
"""Python_for

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KYrTSJPD48S20wHFIJInHwpgAZ2p4art
test
"""

for _ in range(10) : #변수i는 실행문에서 사용되지 않는 루프변수이므로 언더스코어를 통해 익명화 시킴 / 큰 의미 없음 / 단순반복이면 i 생략한다 정도
  print('Welcome to everyone!!!')

from google.colab import drive
drive.mount('/content/drive')

list(range(5))

for i in range(2,101,2) :
  print(i)

for i in range (1, 100, 2) :
  print(i)

a = [1,2,3,4,[5,6,7],8,9]
a[4][1]

for i in range(5) :
  print(i, end = ' ') #end를 넣으면 옆으로 출력 됨

for i in range(0, 5) :
  print(i, end = ' ')

s = 0
for i in range(1, 11) :
  s = s + i #s += i도 가능
print('1에서 10까지의 합 ; ', s)

s = 0
for i in range(1, 11) :
  s = s + i #s += i도 가능
  print('i = {}, s = {}' .format(i, s)) #,format 순서대로 또는 키워드를 사용하여 값을 지정
print('1에서 10까지의 합 : ', s)

n = int(input('합계를 구할 수를 입력하세요 : '))
s = 0
for i in range(0, n) : #시작점이 0부터이기 때문에
  s = s + (i+1) #(i+1)을 넣어준다
  print('i = {}, s = {}' .format(i, s))
print('1부터 {}까지의 합은 {}'.format(n, s))

for i in 'hello' :
  print(i)

fruits = ['사과', '바나나', '오렌지']
for fruits in fruits :
  print(fruits)

numbers = [10, 20, 30, 40, 50]
print('리스트 항목 값의 합 : ', sum(numbers)) #내장함수 sum 사용

for i in range(5) :
  print(i)

a = ('15')
for i in a[0:2] :
  print(i, end = '')

n = 5 #외부 for 루프는 n번 실행, i는 0에서 6까지 증가
for i in range(n) :
  st = ''
  for j in range(i) : # 내부 for 루프는 i번 실행
    st = st + ' ' # 공백을 i개 추가함
  print(st + '#') # 공백 추가 후 '#'출력

n = 7 # 외부 for 루프는 n번 실행, i는 0에서 6까지 증가
for i in range(n) :
  print(' '*i + '#') # 공백을 i번 추가한 뒤 '#' 출력

n = 5
for i in range(n) : # 외부 for문을 5번 실행
  for j in range(n - (i+1)): # 공백을 출력
    print(' ', end = '')
  for j in range(2 * i +1): # +를 출력
    print('+', end = '')
  print()

name = "Bob"
score = 85.5
print("이름: {}, 점수: {}".format(name, score))
print("이름: {0}, 점수: {1}".format(name, score)) # 인덱스 지정
print("이름: {n}, 점수: {s}".format(n=name, s=score)) # 키워드 지정

n = int(input('정수를 입력하세요 : '))
s = 0
for i in range(0, n) :
  s = s + (i+1)
  print('i = {}, s + {}'.format(i, s))
print(s)

color = 'red'
size = '5'
print('이 공의 색은 {}이고, 크기는 {}cm이다' .format(color, size))

# 과자 봉지별 개수 (리스트)
cookie_counts = [5, 2, 8, 3]

# 지금까지 센 총 과자 개수 (처음엔 0개)
total_cookies = 0

# for 문: 각 과자 봉지의 개수를 i라는 변수로 받아서 확인
for i in cookie_counts:
    print("이번 봉지에 들어있는 과자 개수:", i)
    total_cookies = total_cookies + i  # i (현재 봉지의 과자 개수)를 총 개수에 더하기

# 최종적으로 센 총 과자 개수 확인
print("모든 과자의 총 개수:", total_cookies)

n = int(input('정수를 입력하세요 : '))
s = 0
for i in range(n) :
  print(i+1)
  s = s + (i+1)
print(s)

count = 0
while count < 2:
    print("Count is:", count)          # 이 줄은 while 루프 코드 블록에 속함
    count = count + 1                         # 이 줄도 while 루프 코드 블록에 속함

print("Loop finished.")

for i in range(10) :
  print('{}'.format(i))

test_list = ['one', 'two', 'three']
for i in test_list :
  print(i)

a = [(1,2), (3,4), (5,6)]
for (first, last) in a :
  print(first + last)

marks = [90, 25, 67, 45, 80]
number = 0
for mark in marks :
  number = number + 1
  if mark >= 60 :
    print('{}번 학생은 합격입니다.' .format(number))
  else :
    print('%d번 학생은 불합격입니다.' % number)

sum = 0
for i in range(1, 11) :
  sum = sum + i
print(sum)

for i in range(2, 10) :
  for j in range(1, 10) :
      print(i * j, end=' ')
  print('')

result = [x * y for x in range(2, 10) for y in range (1, 10)]

result =  []
for x in range (2, 10):
  for y in range (1, 10):
    result.append(x * y)

n = 5
st = ''
for i in range(n) :
  st = st + ' '
  for j in range(1) :
    print(st,'#', end = '')
  print('')

for i in [0,1,2,3,4] : #range(5)와 동일한 리스트 / 총 5줄 짜리로 만들겠다는 뜻
  str = '' #외부 루프의 코드블럭 / 제일 앞에 아무것도 없는 문자를 넣어서 줄을 시작함
  for j in range(i) : #아래의 str = str + ' '를 i번 실행한다는 뜻
    str = str + ' '
  print(str +'#')

for i in range(5) :
  print(' ' * i, '#')

for i in range(5) :
  print(' ' * (5-(i+1)), '#')

n = int(input('정수 : '))
for i in range(n) :
  st = ''
  for j in range(i) :
    st = st + ' '
  print(st+'#')

