# -*- coding: utf-8 -*-
"""Python_tuple/dict

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13aNbhVDkTDYvjLHWOGNLrRj1L0JH9ojK
"""

#딕셔너리
person = {'이름':'홍길동', '나이':26, '몸무게':82}
print(len(person))
print('이름' in person)
print('직업' in person)
print('홍길동' in person)

person = {'이름':'홍길동', '나이':26, '몸무게':82}
for key in person:
  print(f'{key} : {person[key]}')

person = {'이름':'홍길동', '나이':26, '몸무게':82}
print(*(f'{key} : {person[key]}' for key in person))

#튜플

a = (100) # 이건 정수로 선언됨 / 잘못된 튜플 선언
print(a)
print(type(a))
b = (100,) # ,를 붙여야 튜플로 선언됨
print(b)
print(type(b))

t = (0, 1, 2, 3, 4)
t[0] = 100 #튜플은 불변이므로 할당 연산은 오류 발생

#패킹
a = (1, 2)
print(a[0])
print(a[1])

#언패킹
c = (3, 4) #튜플 패캉
d, e = c #튜플 언패킹
print(d)
print(e)

a = 100
b = 200
print('swap 이전 : a =', a, 'b = ', b)
temp = a #temp = 100 / a = 공백 / b = 200
a = b #temp = 100 / a = 200 / b = 공백
b = temp #temp = 공백 / a = 200 / b = 100
print('swap 이후 : a =', a, 'b = ', b)

#스왑 - 두 변수의 값을 교환하는 작업
a = 100
b = 200
print('swap 이전 : a =', a, 'b = ', b)
a ,b = b, a # a, b = b, a 라는 한 줄을 이용해 값을 교환 / 일종의 백패킹
print('swap 이후 : a =', a, 'b = ', b)

# list()와 tuplr()을 활용하여 튜플 값을 변환
t_fruits = ('apple', 'orange', 'water melon')
print('변경 전 :', t_fruits)
f_list = list(t_fruits) # 튜플을 리스트로 변환
f_list[1] = 'kiwi' # 리스트의 항목을 변경
t_fruits = tuple(f_list) # 리스트를 튜플로 변환
print('변경 후 :', t_fruits)

def area_and_circum(radius): #원의 면적과 둘레 구하기
  area = 3.14 * radius ** 2
  circum = 2 * 3.14 * radius
  return area, circum #튜플을 반환함 - 반환값 (area, circum)

r = 4
a, c = area_and_circum(r) # 반환받은 값을 언패킹함
print(f'반지름이 {r}인 원의 면적과 둘레 : {a}, {c}')

def square(x, y):
  return x*x, y*y

x = 10
y = 20
x_sp, y_sp = square(x, y) # x, y의 제곱을 각각 반환
print(f'{x} 제곱 = {x_sp}, {y}제곱 = {y_sp}')

