# -*- coding: utf-8 -*-
"""Python_if

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CHlpSpU58WuCjiz_B4n-52MFqUWgxSHM
"""

#if 조건문 예제
age = int(input('나이를 입력하세요 :')) #int로 형변환을 해야
if age < 20 : #비교연산자가 작동을 함
  print('청소년 할인')

walk_count = int(input('걸음 수를 입력하세요 :'))
if walk_count >= 1000 :
  print('목표 달성')

game_score = int(input('게임 점수를 입력하세요 :'))
if game_score >= 1000 :
  print('고수입니다.')

game_score = 800
if game_score >= 1000 :
  print('당신은 고수입니다')

print('두 숫자가 같은지 확인해보세요')
num_a = int(input('숫자 A를 입력하세요 :'))
num_b = int(input('숫자 B를 입력하세요 :'))
if num_a == num_b : #=는 ~이다라는 선언을 하는 것이고, 같다라는 뜻은 ==나 :=를 사용한다
  print('두 값이 일치합니다.')

number = int(input('정수를 입력하세요 :'))
if number % 3 == 0 : #[3으로 나눈 값의 나머지가 없다] 라는 뜻임
  print(number, '은/는 3의 배수입니다.') #number는 그대로 표시되게 하고 그 이후의 문자열을 ''를 통해 출력되게 함

#and를 활용한 공배수 구하기
number = int(input('정수를 입력하세요 :'))
if number % 3 == 0 and number % 5 == 0 :
  print(number, '은/는 3의 배수이면서 5의 배수입니다.')

#else 적용 예시
hour = int(input('시간을 입력하세요 : '))
if hour < 12 :
  print('오전입니다.')
else :
  print('오후입니다.')

num = int(input('정수를( 입력하세요 : '))
if num > 0 :
  print('양수입니다.')
else:
  print('음수입니다.')

#if문 안에 if문 2중 if문
num = int(input('정수를 입력하세요 : '))
if num < 0 :
  print(num,'은/는 음수입니다')
else :
  print(num, '은/는 음수가 아닙니다.')
  if num % 2 == 0 :
    print(num, '은/는 짝수입니다.')
  else :
    print(num, '은/는 홀수입니다')

pip install nbconvert

num = int(input('양의 정수를 하나 입력하세요 : '))
if num % 2 == 0:
  print(num, '은/는 짝수입니다')
else:
  print(num, '은/는 홀수입니다')

gameScore = int(input('게임 점수를 입력하세오 : '))
if gameScore > 1000 :
  print('당신은 고수입니다.')
else:
  print('당신은 초보입니다.')

adult = int(input('당신은 성인인가요? (성인이면 1, 미성년이면 0)'))
marry = int(input('결혼을 하셨나요? (기혼이면 1, 미혼이면 0)'))
if adult == 1 and marry == 1 :
  print('당신은 결혼한 성인입니다')
if adult == 0 and marry == 1 :
  print('당신은 결혼한 미성년자입니다')
if adult == 1 and marry == 0 :
  print('당신은 미혼인 성인입니다')
if adult == 0 and marry == 0 :
  print('당신은 미혼인 미성년자입니다')

a = 0
b = 0
a == b

a = 0
b = 0
a is b

num = int(input('정수를 입력하세요 : '))
if num >= 1 and num <= 10 :
  print('1 이상, 10이하의 숫자 입니다.')
  if num % 2 == 0 :
    print('짝수입니다.')
  else :
    print('홀수입니다.')
else :
  print('1 미만, 10 초과하는 정수입니다.')

age = int(input('나이를 입력하세요 : '))
if 10 <= age <= 19 :
  print('청소년입니다.')

age = (input('나이를 입력하세요 : '))
print(int(age[0]),'0% 만큼 할인 받아가세요!')

score = int(input('점수를 입력하세요 : '))
if score >= 90 :
  grade = 'A'
elif score >= 80 :
  grade = 'B'
elif score >= 70 :
  grade = 'C'
elif score >= 60 :
  grade = 'D'
else :
  grade = 'F'
print('당신의 등급은', grade)

speed = int(input('자동차의 속도를 입력하세요(단위 km/h) : '))
if speed >= 100 :
  count = '고속'
elif speed >= 60 :
  count = '중속'
else :
  count = '저속'
print('당신은 지금', count,'으로 달리고 있습니다.')

money = True
if money :
  print('택시타라')
else:
  print('걸어가라')

