# -*- coding: utf-8 -*-
"""Python_line

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TG5vmGRupZTm6rHjYGOuwQSQXSEZDoRO
"""

list1 = list(range(1,5))
list1

a_list = ['a', 'b', 'c', 'd', 'e']
a_list.append('f') #이미 존재하느 리스트의 맨 마지막에 새로운 항목 추가
a_list

n_list = [10, 20, 30, 40]
n_list.append(50)
n_list

n_list = [11, 22, 33, 44, 55, 66]
print(n_list)

del n_list[3]
print(n_list)

n_list.pop(2)

del n_list[2:]
n_list

n_list.append(33)

n_list.append(44)

n_list.append(55)

n_list.append(66)

10 in n_list

n_list

11 not in n_list

n_list.remove(33)

n_list

if 55 in n_list:
  n_list.remove(55)
print(n_list)

a = [1, 2, 3, 4, 5, 6]
if 5 in a:
  a.remove(5)
print(a)

nation = ['Korea', 'China', 'Russia', 'Mylaysia', 'Nepal']
if 'Japen' not in nation:
  print('Japan is not in the list')

if 'Russia' in nation:
  print('Russia is in the list')

list1 = [1, 2, 3, 4, 5, 6] # 문자열듀 가능 / 찾는 순서는 사전과 동일
print(max(list1))
print(min(list1))
print(sum(list1))

list1 = [11, 22, 33, 44]
list1.append([55, 66]) #리스트 안에 리스트 추가
list1

list2 = [11, 22, 33, 44]
list2.extend([55, 66]) #리스트 안에 항목 추가
list2

list1 = [1, 2, 3]
list2 = [4, 5, 6]
list3 = list1 + list2
list3

print('list1*2 =', list1*2)

list1 = [10, 20, 30, 40, 50]
i = 0
for n in list1:
  list1[i] = n * 10
  i += 1
print(list1)

list1 = [10, 20, 30, 40, 50]
list1 = [n * 10 for n in list1] #리스트 축약 표현
print(list1)

a_list = [10, 20, 30, 40, 50, 60, 70, 80]
a_list[0:9:2]

