# -*- coding: utf-8 -*-
"""Python_set

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xk5UB09Lj_dItxUCfEYq40RxXxKCjHw0
"""

days_list = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
days_set = set(days_list) #리스트를 집합으로 만들기
print(days_set)
fruits_tuple = ('apple', 'banana', 'orange', 'watermelon')
fruits_set = set(fruits_tuple) #튜플을 집합으로 만들기
print(fruits_set)
h_str = 'hello'
h_str = set(h_str) # 문자열을 집합으로 만들기
print(h_str) # 문자열 'l'의 중복을 허용하지 않음

#조건문을 활용한 곱집합
def product_set(set1, set2):
    res = set()
    for i in set1:
        for j in set2:
            res = res | {(i, j)} #이중 for 루프를 이용한 곱집합
    return res

A = {1, 3} #집합 A의 원소
B = {2, 4} #집합 B의 원소
AxB = product_set(A, B)
print('A =', A)
print('B =', B)
print('A x B =', AxB)

