# -*- coding: utf-8 -*-
"""Python_while

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y1lDboQ7vvyVJsUMWbKjJ8oAHtcaDLvN
"""

#while문
i = 0
while i < 5:
  print('환영합니다')
  i += 1 # i = i + 1

n = int(input('합계를 구할 수를 입력하시오 : '))
s = 0
i = 1
while i <= n :
  s = s + i
  i += 1
print('1부터 {}까지의 합은 {}'.format(n, s))

selected = None
while selected not in ['가위', '바위', '보']: #가위, 바위, 보 가 포함되어있지 않으면
  selected = input('가위, 바위, 보 중에서 선택하시오 : ') #이 내용을 반복한다.
print('선택한 값은 : ', selected)

#break
st = 'Programming'
for ch in st :
  if ch in ['a', 'e', 'i', 'o', 'u']: # 이 조건이 참이면
    break # for문을 끝내고 코드블럭을 빠져나감
  print(ch)
print('The end')

#위와 동일한 내용
for i in ('Programming') :
  if i in ['a', 'e', 'i', 'o', 'u']:
    break
  print(i)
print('The end')

#continue
st = 'Programming'
for ch in st :
  if ch in ['a', 'e', 'i', 'o', 'u']: #이 조건이 참이면
    continue # for문 시작점으로 돌아감
  print(ch)
print('The end')

#위와 동일
for i in ('Programming') :
  if i in ['a', 'e', 'i', 'o', 'u']:
    continue
  print(i)
print('The end')

